services:

  minio:
    image: chainguard/minio:latest
    # Run as root so existing volume (created by previous root MinIO) is writable; no data loss
    user: "0:0"
    container_name: minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    #production only
    #command: server /data
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console UI
    networks:
      - storage-network
    volumes:
      - ./volumes/minio_data:/data

  # garage:
  #   image: dxflrs/garage:v2.2.0
  #   container_name: garage
  #   env_file:
  #     - .env      
  #   ports:
  #     - "3900:3900"   # S3 API
  #     - "3901:3901"   # Admin API
  #   volumes:
  #     - ./volumes/garage_data:/var/lib/garage/data
  #     - ./volumes/garage_meta:/var/lib/garage/meta
  #     - ./garage.toml:/etc/garage.toml:ro
  #   networks:
  #     - storage-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3900/health"]
  #     interval: 15s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 20s

  # garage-ui:
  #   image: khairul169/garage-webui:latest
  #   container_name: garage-ui
  #   env_file:
  #     - .env
  #   ports:
  #     - "3909:3909"   # Web UI
  #   environment:
  #     API_BASE_URL:  ${GARAGE_ADMIN_ENDPOINT}
  #     S3_ENDPOINT_URL: ${GARAGE_S3_ENDPOINT}
  #     S3_ACCESS_KEY_ID: ${GARAGE_ACCESS_KEY}
  #     S3_SECRET_ACCESS_KEY: ${GARAGE_SECRET_KEY}      
  #   volumes:
  #     - ./garage.toml:/etc/garage.toml:ro
  #   depends_on:
  #     - garage
  #   networks:
  #     - storage-network

  storage-service:
    container_name: storage-service
    build:
      context: .   
      dockerfile: src/API/Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5034:8080"
    networks:
      - storage-network
    volumes:
      - ./error-codes/errors.json:/app/errors.json:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      - storage-network
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    networks:
      - storage-network
    depends_on:
      - elasticsearch
    restart: always

networks:
  storage-network:
    driver: bridge
    name: storage-network